import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { InstallConfig } from "../types";

export async function writeEnvFile(cfg: InstallConfig): Promise<string> {
  const databaseUrl = `postgresql://orqestra:${cfg.postgresPassword}@postgres:5432/orqestra`;
  const isLocal = cfg.mode === "local";

  const lines: string[] = [
    "# Generated by orqestra-install",
    `# Mode: ${cfg.mode}`,
    "",
    "# --- Postgres ---",
    `POSTGRES_PASSWORD=${cfg.postgresPassword}`,
    `DATABASE_URL=${databaseUrl}`,
    "",
    "# --- Redis ---",
    "REDIS_URL=redis://redis:6379",
    "",
    "# --- Auth / Internal ---",
    `BETTER_AUTH_SECRET=${cfg.betterAuthSecret}`,
    `BETTER_AUTH_URL=${isLocal ? "http://localhost:4000" : `https://api.${cfg.siteDomain}`}`,
    `INTERNAL_API_SECRET=${cfg.internalApiSecret}`,
    "",
    "# --- Orchestrators ---",
    "ORCHESTRATOR_JUPYTER_URL=http://orchestrator-jupyter:8080",
    "ORCHESTRATOR_HOSTING_URL=http://orchestrator-hosting:8080",
    "",
    "# --- Domain ---",
    `SITE_DOMAIN=${cfg.siteDomain}`,
    "",
    "# --- Cloudflare DNS (Traefik DNS-01) ---",
    `CF_DNS_API_TOKEN=${cfg.cfDnsApiToken ?? ""}`,
    "",
    "# --- Web (public) ---",
  ];

  if (isLocal) {
    lines.push(
      "NEXT_PUBLIC_API_URL=http://localhost:4000",
      "NEXT_PUBLIC_WS_URL=ws://localhost:4001",
    );
  } else {
    lines.push(
      `NEXT_PUBLIC_API_URL=https://api.${cfg.siteDomain}`,
      `NEXT_PUBLIC_WS_URL=wss://ws.${cfg.siteDomain}`,
    );
  }

  if (isLocal) {
    lines.push(
      "",
      "# --- Local-mode overrides (binds containers on LAN if set) ---",
      "LOCAL_BIND_IP=",
      "LOCAL_PUBLIC_HOST=",
    );
  } else {
    lines.push(
      "",
      "# --- Reserved RAM scheduler keeps off model budget (MB) ---",
      "RESERVED_RAM_MB=2048",
    );
  }

  if (cfg.letsEncryptEmail) {
    lines.push("", `LETSENCRYPT_EMAIL=${cfg.letsEncryptEmail}`);
  }

  if (cfg.anthropicApiKey) {
    lines.push("", "# --- Diagnostics (optional) ---", `ANTHROPIC_API_KEY=${cfg.anthropicApiKey}`);
  }

  const path = join(cfg.installDir, ".env");
  await writeFile(path, lines.join("\n") + "\n", { mode: 0o600 });
  return path;
}
